// SPDX-License-Identifier: UNLICENSED
pragma solidity 0.8.23;

/// NOTE: Functions here are stubs for the solidity compiler to generate the right interface.
/// The deployed library is generated bytecode from the circomlib toolchain

library PoseidonT3 {
    function poseidon(bytes32[2] memory input) public pure returns (bytes32) {}
}
